# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
$schema: https://json-schema.org/draft/2020-12/schema
$id: Settings.schema.yaml
title: Font Settings
description: Optional settings for configuring fonts on a Platen site.
schematize:
  details: |
    Defines the map of base font settings for the theme. The existing value is a map of
    settings that define the font families for body text and code elements.

    You can add new keys or replace the values for existing ones. You don't need to keep the
    full list of all styles in your own configuration file. Only specify the values you want
    to add or replace.

    For more information on creating your own settings, see [sref:Defined Font Settings].

    <!-- Reference Links -->
    [sref:Defined Font Settings]: Platen.Site.Theme.Fonts.Settings.pattern-any
type: object
properties:
  Body:
    title: Body Font Settings
    description: Settings for the font of body text.
    schematize:
      skipSchemaRender: true
      details: |
        Defines the font settings for body text on the site. By default, the selector is `body`,
        which applies the fonts to everything. The family is set to `'Roboto', sans-serif`. The
        Roboto font is bundled with Platen.
    type: object
    default:
      Selector: body
      Family: "'Roboto', sans-serif"
  Code:
    title: Code Font Settings
    description: Settings for the font of inline and block code.
    schematize:
      skipSchemaRender: true
      details: |
        Defines the font settings for inline and block code on the site. By default, the selector is
        `code`, which applies the fonts to everything in that element. The family is set to
        `'Roboto Mono', monospace`. The Roboto Mono font is bundled with Platen.
    type: object
    default:
      Selector: code
      Family: "'Roboto Mono', monospace"
patternProperties:
  ".":
    type: object
    title: Defined Font Settings
    description: |
      All settings groups must define the [sref:`Selector`] and [sref:`Family`] properties. This
      allows theme developers and site maintainers to override where the setting gets applied and
      what font families get applied.

      <!-- Reference Links -->
      [sref:`Family`]: Platen.Site.Theme.Fonts.Settings.pattern-any.family
      [sref:`Selector`]: Platen.Site.Theme.Fonts.Settings.pattern-any.selector
    schematize:
      href: pattern-any
    properties:
      Selector:
        title: CSS Selector
        description: Specify a valid SCSS selector to set the font family for.
        schematize:
          weight: 1
          details: |
            Specify a valid SCSS selector to set the font family for. If this value isn't specified,
            Platen uses the downcased name of the group as the selector. For example, `Details`
            would use `details` as the SCSS selector.

            We strongly encourage you to provide a value for this setting instead of relying on that
            default behavior.

            For more information about SCSS selectors, see [the SCSS documentation][scss-docs].

            <!-- Reference Links -->
            [scss-docs]: https://sass-lang.com/guide
        type: string
      Family:
        title: Font Family
        description: Specify a font-family list to apply to the specified selector.
        schematize:
          weight: 2
          details: |
            Specify a valid [sref:`font-family`] to apply to the defined selector. This value can
            include any fonts defined in [sref:`Theme.Fonts.Styles`] or a default web font.

            <!-- Reference Links -->
            [sref:`font-family`]: mdn.css:font-family
            [sref:`Theme.Fonts.Styles`]: Platen.Site.Theme.Config.Fonts.Styles
        type: string
      Mixins:
        title: SCSS Mixins to Include
        description: Specify a font-family list to apply to the specified selector.
        schematize:
          weight: 3
          details: |
            Specify the name of a [mixin] defined in [sref:`Theme.Fonts.Styles`] to include it for
            the specified selector.

            <!-- Reference Links -->
            [mixin]: https://sass-lang.com/documentation/at-rules/mixin
            [sref:`Theme.Fonts.Styles`]: Platen.Site.Theme.Config.Fonts.Styles
        type: array
        items:
          type: string
