# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
$schema: https://json-schema.org/draft/2020-12/schema
$id: config.schema.yaml
title: Theming Options
description: Optional settings for theming a Platen site.
schematize:
  details: |
    The Platen theme options...
type: object
properties:
  mode:
    title: Display Mode
    description: >-
      Specifies whether the site should show light or dark theme or use the user's OS preference
      setting.
    schematize:
      weight: 1
      details: |
        Specifies whether the site should display the light theme (`light`), dark theme (`dark`),
        or the theme that matches the user's OS preferences (`auto`).

        The default is `auto`.
    type: string
    enum:
      - auto
      - light
      - dark
    default: auto
  variables:
    title: Variables
    description: Variables to insert for SCSS and CSS.
    schematize:
      weight: 2
      skipSchemaRender: true
      details: |
        Defines several different groups of variables to insert into the SCSS that defines how the
        site is displayed.

        You can add new keys or replace the values for existing ones. You don't need to keep the
        full list of all variables in your own configuration file. Only specify the values you want
        to add or replace.

        The variables are added to the SCSS in the following order:

        1. [sref:`basic_scss`] is loaded first, because these variables have no dependencies.
        2. [sref:`calculated_scss`] is loaded next, because these variables are expected to use
           values defined in `basic_scss` for convenience.
        3. [sref:`light_css`] and [sref:`dark_css`] are loaded next. They're independent of each
           other, but may rely on values defined in [sref:`basic_scss`] or [sref:`calculated_scss`].

        [sref:`basic_scss`]: Platen.Site.theme.variables.basic_scss
        [sref:`calculated_scss`]: Platen.Site.theme.variables.calculated_scss
        [sref:`light_css`]: Platen.Site.theme.variables.light_css
        [sref:`dark_css`]: Platen.Site.theme.variables.dark_css
    type: object
    properties:
      basic_scss:
        $ref: ./variables/basic_scss.yaml
        schematize:
          weight: 1
      calculated_scss:
        $ref: ./variables/calculated_scss.yaml
        schematize:
          weight: 2
      light_css:
        $ref: ./variables/light_css.yaml
        schematize:
          weight: 3
      dark_css:
        $ref: ./variables/dark_css.yaml
        schematize:
          weight: 4
  styles:
    title: Styles
    description: SCSS Style modules
    schematize:
      weight: 3
      skipSchemaRender: true
      details: |
        Defines several different groups of style modules to insert into the SCSS that defines how
        the site is displayed.

        You can add new keys or replace the values for existing ones. You don't need to keep the
        full list of all variables in your own configuration file. Only specify the values you want
        to add or replace.

        The styles are added to the SCSS in a non-deterministic order.
    type: object
    properties:
      base:
        $ref: ./styles/base.yaml
        schematize:
          weight: 1
      platen:
        $ref: ./styles/platen.yaml
        schematize:
          weight: 2
      mobile:
        $ref: ./styles/mobile.yaml
        schematize:
          weight: 3
      wide:
        $ref: ./styles/wide.yaml
        schematize:
          weight: 4
      markdown:
        $ref: ./styles/markdown.yaml
        schematize:
          weight: 5
      utils:
        $ref: ./styles/utils.yaml
        schematize:
          weight: 6
  fonts:
    title: Font Options
    description: Add and configure fonts
    schematize:
      weight: 4
      skipSchemaRender: true
      details: |
        Defines the set of fonts the theme should add and configures how to apply those fonts to
        different elements in the theme.

        The [sref:`styles`] property controls the addition of fonts as an overridable array of font
        declarations. The [sref:`settings`] property controls where the fonts are used.

        [sref:`styles`]: Platen.Site.theme.config.fonts.styles
        [sref:`settings`]: Platen.Site.theme.config.fonts.settings
    type: object
    properties:
      styles:
        title: Font Options
        description: Optional settings for configuring fonts on a Platen site.
        schematize:
          weight: 1
          details: |
            Defines the array of fonts to load for the theme. The existing value is an array that makes the
            theme's default fonts (the Roboto family) available.

            If you define this setting in your site or theme, you _replace_ the existing set of fonts. To
            reinclude the theme's default fonts, make sure to include `roboto` in the array.

            For example, if a theme defined it's own `spectral` font family, it could re-add the roboto font
            with the following configuration:

            ```yaml
            Fonts:
              Styles:
                - spectral
                - roboto
            ```

            There are two options for defining font style modules.

            1. **Simple Font Modules**

               Simple font module declarations are strings matching the name of an SCSS module in
               the `assets/fonts` folder. For example, to add the module in
               `assets/fonts/_spectral.scss`, specify `spectral`. This value is case sensitive.
            1. **Mapped Font Modules**

               [sref:Mapped font modules] provide more control over the importing of an SCSS module with
               fonts. Add each item as a map with the [sref:`import_name`] key defined.

               The [sref:`import_name`] must be a string that matches the name of an SCSS module in
               the `assets/fonts` folder. For example, to add the module in
               `assets/fonts/_spectral.scss`, specify `spectral`. This value is case sensitive.

               You can also specify the [sref:`weight`] key to control the order the SCSS modules
               are loaded. All mapped declarations are loaded before unmapped modules. All weighted
               modules are loaded before unweighted modules. Weighted modules are loaded in order
               from lowest weight to highest.

               [sref:`import_name`]: Platen.Site.theme.fonts.mapped_style.import_name
               [sref:`weight`]: Platen.Site.theme.fonts.mapped_style.weight
               [sref:Mapped font modules]: Platen.Site.theme.fonts.mapped_style
        type: array
        items:
          oneOf:
            - type: string
              description: >-
                The name of an SCSS module in the `assets/fonts` folder. For example, to add the module in
                `assets/fonts/_spectral.scss`, specify `spectral`. This value is case sensitive.
            - $ref: ./fonts/mapped_style.yaml
      settings:
        $ref: ./fonts/settings.yaml
        schematize:
          weight: 2
  printing:
    title: Printing Options
    description: Configure and style the site for printing
    schematize:
      weight: 5
      skipSchemaRender: true
      details: |
        Defines the style modules to use when a site visitor prints a page.

        The [sref:`styles`] property controls the importing of SCSS modules as a map.

        [sref:`styles`]: Platen.Site.theme.printing.styles
    type: object
    properties:
      styles:
        $ref: ./printing/styles.yaml
        schematize:
          weight: 1
