# Update to your own settings for URL/title
baseURL: https://platen.io/
title: Platen
themesDir: ../modules
contentDir: ../content
dataDir: ../data

module:
  replacements: >-
    github.com/platenio/platen/modules/platen -> platen,
    github.com/platenio/platen/modules/schematize -> schematize,
    github.com/platenio/platen/modules/toroidal -> toroidal,
    github.com/platenio/platen/modules/memo -> memo
  imports:
    - path: github.com/platenio/platen/modules/memo
    - path: github.com/platenio/platen/modules/toroidal
      mounts:
        - source: archetypes
          target: archetypes
        - source: assets
          target: assets
        - source: docs
          target: content/modules/toroidal
        - source: i18n
          target: i18n
        - source: layouts
          target: layouts
        - source: static
          target: static
    - path: github.com/platenio/platen/modules/schematize
      mounts:
        - source: archetypes
          target: archetypes
        - source: assets
          target: assets
        - source: docs
          target: content/modules/schematize
        - source: i18n
          target: i18n
        - source: layouts
          target: layouts
        - source: static
          target: static
    - path: github.com/platenio/platen/modules/platen
      mounts:
        - source: archetypes
          target: archetypes
        - source: assets
          target: assets
        - source: docs
          target: content/modules/platen
        - source: i18n
          target: i18n
        - source: layouts
          target: layouts
        - source: static
          target: static

disablePathToLower: true
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
  tableOfContents:
    startLevel: 1
    endLevel: 6

languages:
  en:
    languageName: English
    contentDir: ../content
    weight: 1

menu:
  after:
    - name: Contact
      url: /contact
      weight: 5
    - name: Hugo
      url: https://gohugo.io/
      weight: 10
    - name: Hugo Book
      url: https://github.com/alex-shpak/hugo-book
      weight: 20
  before:
    - name: Posts
      url: /posts
      weight: 10
