description: A toolkit for interactive digital books.
images:
  - /images/logo.svg

schematize:
  reference_map:
    mdn:
      sref_suffix: in the MDN documentation
      sref_base: https://developer.mozilla.org/docs
      css:
        sref_base: https://developer.mozilla.org/docs/Web/CSS
      html:
        element:
          sref_base: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
        attribute:
          sref_base: https://developer.mozilla.org/docs/HTML/Attributes
        global_attribute:
          sref_base: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

platen:
  theme:
    mode: auto                                # BookTheme
  display:
    table_of_contents:
      minimum_level: 1
      maximum_level: 6
    date_format: "January 2, 2006"             # BookDateFormat
    menu:
      root_section: /                          # BookSection
      before_injection:
        entries:
          - feature: toroidal
            weight: 1
            page_path: sites/platen
            display_name: Platen Sites
    logo:
      url: /images/logo.svg                   # BookLogo
  features:
    search:                                   # booksearch
      enabled: true
    comments:                                 # bookcomments
      enabled: true
    pwa:                                      # bookserviceworker
      enabled: true
    portable_links:                            # BookPortableLinks
      enabled: true
  repository:
    url: "https://github.com/platenio/platen" # BookRepo
    commit_path: commit                        # BookCommitPath
    edit_path: edit/main                       # BookEditPath
    content_root: 'content'
    mounted_paths:
      - source: modules/platen/_docs
        target: modules/platen
      - source: modules/toroidal/_docs
        target: modules/toroidal
      - source: modules/schematize/_docs
        target: modules/schematize
  multilingual:                               # BookTranslatedOnly
    translated_only: false

Toroidal:
  WebringName: Platen Site Ring