description: A toolkit for interactive digital books.
images:
  - /images/logo.svg

Schematize:
  ReferenceMap:
    mdn:
      srefSuffix: in the MDN documentation
      srefBase: https://developer.mozilla.org/docs
      css:
        srefBase: https://developer.mozilla.org/docs/Web/CSS
      html:
        element:
          srefBase: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
        attribute:
          srefBase: https://developer.mozilla.org/docs/HTML/Attributes

Platen:
  Theme:
    Mode: auto                                # BookTheme
  Display:
    TableOfContents:
      MinimumLevel: 1
      MaximumLevel: 6
    DateFormat: "January 2, 2006"             # BookDateFormat
    Menu:
      RootSection: /                          # BookSection
      BeforeInjection:
        Entries:
          - Feature: Toroidal
            Weight: 1
            PagePath: sites/platen
            DisplayName: Platen Sites
    Logo:
      URL: /images/logo.svg                   # BookLogo
  Features:
    Search:                                   # BookSearch
      Enabled: true
    Comments:                                 # BookComments
      Enabled: true
    PWA:                                      # BookServiceWorker
      Enabled: true
    PortableLinks:                            # BookPortableLinks
      Enabled: true
  Repository:
    URL: "https://github.com/platenio/platen" # BookRepo
    CommitPath: commit                        # BookCommitPath
    EditPath: edit/main                       # BookEditPath
    ContentRoot: 'content'
    MountedPaths:
      - Source: modules/platen/docs
        Target: modules/platen
      - Source: modules/toroidal/docs
        Target: modules/toroidal
      - Source: modules/schematize/docs
        Target: modules/schematize
  Multilingual:                               # BookTranslatedOnly
    TranslatedOnly: false

Toroidal:
  WebringName: Platen Site Ring