description: A toolkit for interactive digital books.
images:
  - /images/logo.svg

Schematize:
  ReferenceMap:
    mdn:
      srefSuffix: in the MDN documentation
      srefBase: https://developer.mozilla.org/docs
      css:
        srefBase: https://developer.mozilla.org/docs/Web/CSS
      html:
        element:
          srefBase: https://developer.mozilla.org/en-US/docs/Web/HTML/Element
        attribute:
          srefBase: https://developer.mozilla.org/docs/HTML/Attributes
        global_attribute:
          srefBase: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes

Platen:
  Theme:
    Mode: auto                                # BookTheme
  Display:
    TableOfContents:
      MinimumLevel: 1
      MaximumLevel: 6
    DateFormat: "January 2, 2006"             # BookDateFormat
    Menu:
      RootSection: /                          # BookSection
      BeforeInjection:
        Entries:
          - Feature: Toroidal
            Weight: 1
            PagePath: sites/platen
            DisplayName: Platen Sites
    Logo:
      URL: /images/logo.svg                   # BookLogo
  features:
    search:                                   # booksearch
      enabled: true
    comments:                                 # bookcomments
      enabled: true
    pwa:                                      # bookserviceworker
      enabled: true
    portable_links:                            # BookPortableLinks
      enabled: true
  repository:
    url: "https://github.com/platenio/platen" # BookRepo
    commit_path: commit                        # BookCommitPath
    edit_path: edit/main                       # BookEditPath
    content_root: 'content'
    mounted_paths:
      - source: modules/platen/_docs
        target: modules/platen
      - source: modules/toroidal/_docs
        target: modules/toroidal
      - source: modules/schematize/_docs
        target: modules/schematize
  Multilingual:                               # BookTranslatedOnly
    TranslatedOnly: false

Toroidal:
  WebringName: Platen Site Ring