module:
  hugoVersion:
    extended: true
    min: 0.120.4

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      wrapStandAloneImageWithinParagraph: false
      attribute:
        block: true
  tableOfContents:
    startLevel: 1
    endLevel: 6