module:
  hugoVersion:
    extended: true
    min: 0.104.0

outputFormats:
  Schematize:
    mediaType: application/json
    baseName: schema
    isPlainText: true

params:
  Platen:
    shortcodes:
      schematize:
        enabled: true
        style:
          name: schematize
    markup:
      schematize:
        enabled: true
        partials:
          renderers:
            link: schematize/sref/markup/renderers/links
  Schematize:
    SchemaRoot: schemas